"""Add donation schedule and blood request models

Revision ID: d56b8a6c72b0
Revises: 30e67a6f21ae
Create Date: 2025-10-05 15:31:22.614095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56b8a6c72b0'
down_revision = '30e67a6f21ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 