"""Initial migration

Revision ID: 30e67a6f21ae
Revises: 
Create Date: 2025-06-29 11:16:07.900917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e67a6f21ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hospital_code', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_hospitals_email'), 'hospitals', ['email'], unique=True)
    op.create_index(op.f('ix_hospitals_hospital_code'), 'hospitals', ['hospital_code'], unique=True)
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('emergency_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', name='bloodtype'), nullable=False),
    sa.Column('component', sa.Enum('WHOLE_BLOOD', 'PACKED_CELLS', 'FRESH_FROZEN_PLASMA', 'PLATELETS', 'CRYOPRECIPITATE', name='bloodcomponent'), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('patient_condition', sa.Text(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('response_deadline', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_requests_blood_type'), 'emergency_requests', ['blood_type'], unique=False)
    op.create_index(op.f('ix_emergency_requests_id'), 'emergency_requests', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'HOSPITAL_STAFF', 'BLOOD_BANK_STAFF', 'VIEWER', name='userrole'), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('blood_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', name='bloodtype'), nullable=False),
    sa.Column('component', sa.Enum('WHOLE_BLOOD', 'PACKED_CELLS', 'FRESH_FROZEN_PLASMA', 'PLATELETS', 'CRYOPRECIPITATE', name='bloodcomponent'), nullable=False),
    sa.Column('units_requested', sa.Integer(), nullable=False),
    sa.Column('units_fulfilled', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('NORMAL', 'CRITICAL', 'VERY_CRITICAL', name='priority'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'FULFILLED', 'REJECTED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('patient_details', sa.Text(), nullable=True),
    sa.Column('urgency_notes', sa.Text(), nullable=True),
    sa.Column('expected_use_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blood_orders_blood_type'), 'blood_orders', ['blood_type'], unique=False)
    op.create_index(op.f('ix_blood_orders_id'), 'blood_orders', ['id'], unique=False)
    op.create_index(op.f('ix_blood_orders_priority'), 'blood_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_blood_orders_status'), 'blood_orders', ['status'], unique=False)
    op.create_table('emergency_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emergency_request_id', sa.Integer(), nullable=False),
    sa.Column('responding_hospital_id', sa.Integer(), nullable=False),
    sa.Column('units_offered', sa.Integer(), nullable=False),
    sa.Column('response_message', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('estimated_availability', sa.DateTime(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['emergency_request_id'], ['emergency_requests.id'], ),
    sa.ForeignKeyConstraint(['responding_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_responses_id'), 'emergency_responses', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_hospital_id', sa.Integer(), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('blood_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.Enum('A_POSITIVE', 'A_NEGATIVE', 'B_POSITIVE', 'B_NEGATIVE', 'AB_POSITIVE', 'AB_NEGATIVE', 'O_POSITIVE', 'O_NEGATIVE', name='bloodtype'), nullable=False),
    sa.Column('component', sa.Enum('WHOLE_BLOOD', 'PACKED_CELLS', 'FRESH_FROZEN_PLASMA', 'PLATELETS', 'CRYOPRECIPITATE', name='bloodcomponent'), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('donation_date', sa.DateTime(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('source_location', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=True),
    sa.Column('is_reserved', sa.Boolean(), nullable=True),
    sa.Column('reserved_for_order_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['reserved_for_order_id'], ['blood_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_number')
    )
    op.create_index(op.f('ix_blood_stock_blood_type'), 'blood_stock', ['blood_type'], unique=False)
    op.create_index(op.f('ix_blood_stock_component'), 'blood_stock', ['component'], unique=False)
    op.create_index(op.f('ix_blood_stock_expiry_date'), 'blood_stock', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_blood_stock_id'), 'blood_stock', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('blood_stock_id', sa.Integer(), nullable=False),
    sa.Column('units_allocated', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['blood_stock_id'], ['blood_stock.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['blood_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_blood_stock_id'), table_name='blood_stock')
    op.drop_index(op.f('ix_blood_stock_expiry_date'), table_name='blood_stock')
    op.drop_index(op.f('ix_blood_stock_component'), table_name='blood_stock')
    op.drop_index(op.f('ix_blood_stock_blood_type'), table_name='blood_stock')
    op.drop_table('blood_stock')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_emergency_responses_id'), table_name='emergency_responses')
    op.drop_table('emergency_responses')
    op.drop_index(op.f('ix_blood_orders_status'), table_name='blood_orders')
    op.drop_index(op.f('ix_blood_orders_priority'), table_name='blood_orders')
    op.drop_index(op.f('ix_blood_orders_id'), table_name='blood_orders')
    op.drop_index(op.f('ix_blood_orders_blood_type'), table_name='blood_orders')
    op.drop_table('blood_orders')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_emergency_requests_id'), table_name='emergency_requests')
    op.drop_index(op.f('ix_emergency_requests_blood_type'), table_name='emergency_requests')
    op.drop_table('emergency_requests')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_hospital_code'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_email'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ### 